<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'amadeuslibrary' => '/AmadeusLibrary.php',
                'bgphp\\amadeusflightnumbervalidator' => '/AmadeusFlightNumberValidator.php',
                'bgphp\\flightbookedevent' => '/FlightBookedEvent.php',
                'bgphp\\flightcancelledevent' => '/FlightCancelledEvent.php',
                'bgphp\\flightnumber' => '/FlightNumber.php',
                'bgphp\\flightnumbervalidator' => '/FlightNumberValidator.php',
                'bgphp\\invalidflightnumberexception' => '/InvalidFlightNumberException.php',
                'bgphp\\passenger' => '/Passenger.php',
                'request' => '/AmadeusLibrary.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
